### PR TITLE
fix prototype

### PR DESCRIPTION
**Pull request by remicollet**

### CODE REVIEW

**Comment by kocsismate** [comment]
Since there is a radio silence from @DomBlack, I'm going to merge this PR later this week. IMO, a new release is warranted with all the PHP 8 fixes, so I'd like to handle if Dominic doesn't disagree.

**Comment by jmwendt** [comment]
I'm not familiar with maintaining PECL packages, do you know what would need to be done to release a new version there: https://pecl.php.net/package/scrypt?

**Comment by kocsismate** [comment]
> I'm not familiar with maintaining PECL packages, do you know what would need to be done to release a new version there:

I do not yet know it, but I'll try to release a new version soon. :)

**Comment by jmwendt** [comment]
> > I'm not familiar with maintaining PECL packages, do you know what would need to be done to release a new version there:
> 
> I do not yet know it, but I'll try to release a new version soon. :)

It would be greatly appreciated.

**Pull request merged**
