### PR TITLE
Update scrypt.php

### PR DESCRIPTION
**Pull request by paragonie-scott**
See #44

### CODE REVIEW

**Comment by paragonie-scott** [comment]
Also, maybe remove openssl?

**Comment by DomBlack** [comment]
What's wrong with using `openssl_random_pseudo_bytes` when it reports a cryptographically secure generation?

**Comment by paragonie-scott** [comment]
* https://github.com/ramsey/uuid/issues/80
* https://emboss.github.io/blog/2013/08/21/openssl-prng-is-not-really-fork-safe/
* https://eprint.iacr.org/2016/367
* https://github.com/nodejs/node/issues/5798#issuecomment-198932579

**Comment by paragonie-scott** [comment]
Forgot a big one: https://github.com/paragonie/random_compat/issues/5

**Comment by DomBlack** [comment]
Interesting reads, I removed the OpenSSL option in the 1.4.2 release (after pulling your changes). Thanks for that

**Pull request merged**
