### PR TITLE
fix mem leak on PHP 7

### PR DESCRIPTION
**Pull request by remicollet**
With PHP 7  RETURN_STRINGL always allocate new space (no more 3rd arg, aka copy), need to be freed.

### CODE REVIEW

**Comment by DomBlack** [comment]
@remicollet thanks again for this (I'm not a PHP 7 user myself)

Anything else I should look out for with the change to PHP 7 or am I ok to release 1.4.2 to PECL?

**Comment by remicollet** [comment]
@DomBlack I just add a second "cleanup" commit, nothing critical

Old things

- 20050922 is php-5.1.0
- 20010901 is php-4.2.0
- use PHP_FE_END and ZEND_MOD_END when available (php >= 5.3.7)
- use STANDARD_MODULE_HEADER_EX, so scrypt_deps works (available in 5.3+)

**Comment by remicollet** [comment]
And, BTW, after a quick look, I think everything is ok for a 1.4.2 release ;)

**Comment by remicollet** [comment]
BTW, do you plan to release 1.4.2 soon, or wait a little for more feedback (from other users) ?

P.S. just to know if I push 1.4.1 to my RPM repository or wait for 1.4.2

**Comment by DomBlack** [comment]
I just published 1.4.2, was waiting for feed back on #44 and included the fix in the 1.4.2 release.

**Comment by remicollet** [comment]
Thanks

**Pull request merged**
