### PR TITLE
fix zend_parse_parameters call, fix #46

### LINKED ISSUE #46: 1.4: failed test
Strange, only on RHEL-6 x86_64 and PHP 7.0
```
TEST 2/2 [tests/vectors.phpt]
========DIFF========
002+ 3f0ca2344531c2440c69bab9397fd30dd2ed72b47cb57e3ee83dba2c38318b12465ad8fde304e949fef187b9e1ca7cc8802c98c791322219b05959f503aa0235
003+ 379e9bff2afb37c9f58f947db0c8080fa5fb937b905f1ebbe63ee88a7d6599e29667b3e2b0d11d61c76d61363f89773fdbc9573ebf46373f2d88317b533ef4ef
004+ b63059fab1deaf46ec48a42a2751bb72c353ff5e57791ef265d75f29ed11977d4a7f25017481d7ff45d2cfe29472ee3e6b6c7d433250fd61b9d91066a7e50620
002- fdbabe1c9d3472007856e7190d01e9fe7c6ad7cbc8237830e77376634b3731622eaf30d92e22a3886ff109279d9830dac727afb94a83ee6d8360cbdfa2cc0640
003- 7023bdcb3afd7348461c06cd81fd38ebfda8fbba904f8e3ea9b543f6545da1f2d5432955613f0fcf62d49705242a9af9e61e85dc0d651e40dfcf017b45575887
004- 2101cb9b6a511aaeaddbbe09cf70f881ec568d574a2ffd4dabe5ee9820adaa478e56fd8f4ba5d09ffa1c6d927c40f4c337304049e8a952fbcbf45c6fa77a41a4
========DONE========
FAIL Test scrypt KDF using test vectors. [tests/vectors.phpt] 
```

Ok on i386, with php 5.4, 5.5, 5.6, and other distro (fedora 20-24n RHEL 5 and 7)

### PR DESCRIPTION
**Pull request by remicollet**

### CODE REVIEW

**Comment by DomBlack** [comment]
@remicollet thanks for this, does this fix pass your testing on different distros?

**Comment by remicollet** [comment]
> @remicollet thanks for this, does this fix pass your testing on different distros?
build running...

**Comment by remicollet** [comment]
All build + tests ok on (most combination tested)
- Fedora 20-24
- RHEL 5-7
- i386 + x86_64
- NTS and ZTS
- PHP 5.4, 5.5, 5.6 and 7.0

P.S. can you consider using 3 levels version (like most of PHP extensions)

**Comment by DomBlack** [comment]
Thanks, for this bug fix I will use a third level. (It will be 1.4.1)

**Pull request merged**
